---

# Theme
remote_theme: epidrome/cover-card@main


# Title and tag line
title: endlessrockets
description: social media
avatar: transparent-picture.png
background: ezgif-7-53e7285546.gif


# Online profiles
#dribbble: 'mydribbble'
#facebook: 'myfacebook'
#twitter: #'mytwitter'
#linkedin: 'mylinkedin'
tiktok: 'endlessrockets'
#instagram: 'crevrz'
#pinterest: 'mypinterest'
youtube: 'Endless_Rockets'
#github-user: 'endlessrockets'
#gitlab-user: ''
#codepen: ''
steam: '76561198447052378'
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
reddit: 'endlessrockets'
#rubygems: ''
#medium:  ''
#tumblr: 'mytumblr'
#weibo: 'myweibo'
#vk: 'myvk'
#blog_url: 'myblog.blog.com'
#email: 'hello@example.com'
#messenger: 'myfbchat'
discord: 'vWCXAgvTFR'
roblox: '286790524'
telegram: 'crevrz'


social-links-order:
  - roblox
  - discord
  - youtube
  - tiktok
  - reddit
  - telegram
  - steam



  
# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**




social-links:
  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__
  - name: youtube
    url-pattern: youtube.com/@__USERNAME__
  - name: telegram
    url-pattern: telegram.me/__USERNAME__
  - name: discord
    url-pattern: discord.gg/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-discord
  - name: tiktok
    url-pattern: www.tiktok.com/@__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-tiktok
  - name: steam
    url-pattern: steamcommunity.com/profiles/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-steam
  - name: roblox
    url-pattern: roblox.com/users/__USERNAME__/profile
    url-scheme: https://
    icon-class: <i class="fab fa-roblox"></i>

