---
remote_theme: epidrome/cover-card@main
title: endlessrockets
description: social media
avatar: transparent-picture.png
background: ezgif-7-53e7285546.gif
tiktok: endlessrockets
youtube: Endless_Rockets
steam: "76561198447052378"
reddit: endlessrockets
discord: vWCXAgvTFR
roblox: "286790524"
telegram: crevrz
social-links-order:
  - roblox
  - discord
  - youtube
  - tiktok
  - reddit
  - telegram
  - steam
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f
  - name: twitter
    url-pattern: twitter.com/__USERNAME__
  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__
  - name: google-plus
    url-pattern: plus.google.com/+__USERNAME__
  - name: vk
    url-pattern: vk.com/__USERNAME__
  - name: weibo
    url-pattern: weibo.com/__USERNAME__
  - name: instagram
    url-pattern: instagram.com/__USERNAME__
  - name: flickr
    url-pattern: flickr.com/__USERNAME__
  - name: pinterest
    url-pattern: pinterest.com/__USERNAME__
  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github
  - name: gitlab-user
    url-pattern: gitlab.com/__USERNAME__
    icon-class: fab fa-2x fa-gitlab
  - name: codepen
    url-pattern: codepen.com/__USERNAME__
  - name: stack-overflow
    url-pattern: stackoverflow.com/users/__USERNAME__
  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__
  - name: rubygems
    url-pattern: rubygems.org/profiles/__USERNAME__
    icon-class: far fa-2x fa-gem
  - name: youtube
    url-pattern: youtube.com/@__USERNAME__
  - name: vimeo
    url-pattern: vimeo.com/__USERNAME__
  - name: soundcloud
    url-pattern: soundcloud.com/__USERNAME__
  - name: lastfm
    url-pattern: last.fm/user/__USERNAME__
  - name: medium
    url-pattern: medium.com/@__USERNAME__
  - name: tumblr
    url-pattern: __USERNAME__.tumblr.com
  - name: dribbble
    url-pattern: dribbble.com/__USERNAME__
  - name: keybase
    url-pattern: keybase.io/__USERNAME__
  - name: messenger
    url-pattern: m.me/__USERNAME__
    icon-class: fab fa-2x fa-facebook-messenger
  - name: telegram
    url-pattern: telegram.me/__USERNAME__
  - name: snapchat
    url-pattern: snapchat.com/add/__USERNAME__
  - name: quora
    url-pattern: www.quora.com/profile/__USERNAME__
  - name: discord
    url-pattern: discord.gg/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-discord
  - name: blog_url
    url-pattern: __USERNAME__
    icon-class: fas fa-2x fa-blog
  - name: email
    url-scheme: "mailto:"
    url-pattern: __USERNAME__
    icon-class: far fa-2x fa-envelope-open
  - name: tiktok
    url-pattern: www.tiktok.com/@__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-tiktok
  - name: steam
    url-pattern: steamcommunity.com/profiles/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-steam
  - name: roblox
    url-pattern: roblox.com/users/__USERNAME__/profile
    url-scheme: https://
    icon-class: fab fa-2x fa-roblox
