---
remote_theme: epidrome/cover-card@main
title: endlessrockets
description: social media
avatar: transparent-picture.png
background: ezgif-7-53e7285546.gif
tiktok: endlessrockets
youtube: Endless_Rockets
steam: "76561198447052378"
reddit: endlessrockets
discord: vWCXAgvTFR
roblox: "286790524"
telegram: crevrz
social-links-order:
  - roblox
  - discord
  - youtube
  - tiktok
  - reddit
  - telegram
  - steam
social-links:
  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__
  - name: youtube
    url-pattern: youtube.com/@__USERNAME__
  - name: telegram
    url-pattern: telegram.me/__USERNAME__
  - name: discord
    url-pattern: discord.gg/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-discord
  - name: tiktok
    url-pattern: www.tiktok.com/@__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-tiktok
  - name: steam
    url-pattern: steamcommunity.com/profiles/__USERNAME__
    url-scheme: https://
    icon-class: fab fa-2x fa-steam
  - name: roblox
    url-pattern: roblox.com/users/__USERNAME__/profile
    url-scheme: https://
    icon-class: fab fa-2x fa-roblox
